#!/bin/bash

toggleLayout() {
  CURRENT_LAYOUT=$(setxkbmap -query | awk -F"(,|[ ]+)" '/layout:/ { print $2 }')

  if [[ $CURRENT_LAYOUT = 'us' ]]; then
    setxkbmap de
  else
    setxkbmap us
  fi
}

drawLayout() {
  CURRENT_LAYOUT=$(setxkbmap -query | awk -F"(,|[ ]+)" '/layout:/ { print $2 }')
  echo $CURRENT_LAYOUT
}

case $BLOCK_BUTTON in
  1) toggleLayout && drawLayout ;;  # left click
esac

drawLayout
