#!/bin/bash

toggleLayout() {
  CURRENT_LAYOUT=$(setxkbmap -query | awk -F "(,|[ ]+)" '/layout:/ { print $2 }')

  if [[ $CURRENT_LAYOUT = 'us' ]]; then
    setxkbmap de
  else
    setxkbmap us
  fi
}

drawLayout() {
  setxkbmap -query | awk -F "(,|[ ]+)" '/layout:/ { print $2 }'
}

case $BLOCK_BUTTON in
  1) toggleLayout && drawLayout ;;  # left click
esac

drawLayout
